In [1]:
!pip install torch

  Using cached torch-2.4.1-cp311-cp311-win_amd64.whl (199.4 MB)
  Using cached filelock-3.16.1-py3-none-any.whl (16 kB)
  Using cached networkx-3.3-py3-none-any.whl (1.7 MB)
  Using cached fsspec-2024.9.0-py3-none-any.whl (179 kB)



[notice] A new release of pip available: 22.3 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import torch

In [8]:
import numpy as np

In [4]:
x=torch.tensor([[1,2],[3,4]])
print("Tensor:",x)

Tensor: tensor([[1, 2],
        [3, 4]])


Creating Tensor of Ones

In [6]:
x_ones=torch.ones_like(x)
print("Tensor of Ones:",x_ones)

Tensor of Ones: tensor([[1, 1],
        [1, 1]])


Create Array using Numpy in torch

In [9]:
np_array=np.array(x)
x_np=torch.from_numpy(np_array)
print("Array:",x_np)
print("Datatype of Array:",type(x_np))

Array: tensor([[1, 2],
        [3, 4]])
Datatype of Array: <class 'torch.Tensor'>


Generate Random

In [11]:
x_random=torch.rand_like(x,dtype=torch.float)
print("Random Dataset:",x_random)

Random Dataset: tensor([[0.2651, 0.2537],
        [0.1127, 0.7344]])


In [12]:
shape=(2,3)
random_tensor=torch.rand(shape)
print(random_tensor)

tensor([[0.6301, 0.7206, 0.2129],
        [0.7866, 0.7216, 0.4284]])


Creating Zeros Tensor

In [13]:
zeros_tensor=torch.zeros(shape)
print("Zeros Tensor:",zeros_tensor)
print("Datatype of Tensor:",type(zeros_tensor))

Zeros Tensor: tensor([[0., 0., 0.],
        [0., 0., 0.]])
Datatype of Tensor: <class 'torch.Tensor'>


Creating Random Tensor

In [15]:
tensor = torch.rand(3, 4)
print(tensor)

tensor([[0.4503, 0.1528, 0.3026, 0.4090],
        [0.5660, 0.1228, 0.0214, 0.7195],
        [0.7187, 0.1688, 0.9715, 0.3088]])


Printing Torch Attributes

In [16]:
print("Shape:",tensor.shape)
print("Datatype:",tensor.dtype)
print("Device:",tensor.device)

Shape: torch.Size([3, 4])
Datatype: torch.float32
Device: cpu


Move tensor to GPU

In [19]:
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
    print("Device tensor is stored in ", tensor.device)

Indexing and Slicing

In [20]:
tensor = torch.ones(4, 4)
print(tensor)
tensor1 = torch.zeros(4, 4)
print(tensor1)
tensor2 = torch.cat([tensor, tensor1])
print(tensor2)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


Multiply Operation on Tensor

In [21]:
tensor.mul(tensor1)
tensor * tensor1
tensor.T

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

Inplace Operation on Tensor

In [22]:
tensor.add_(3)
print(tensor)

tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])


tensor to numpy

In [23]:
t = torch.ones(5)
print(t)
n = t.numpy()
print(n)
print(type(n))

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
